package com.example.happybirthday.forage.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Forageable entity to be stored in the forageable_database.
 */
// TODO: annotate this data class as an entity with a parameter for the table name
@Entity(tableName = "forageable")
data class Forageable(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,
    @ColumnInfo(name = "name")
    val name: String,
    @ColumnInfo(name = "address")
    val address: String,
    // TODO: make a custom column name for the inSeason variable that follows SQL column name
    //  conventions (the column name should be in_season)
    @ColumnInfo(name = "in_season")
    val inSeason: Boolean,
    @ColumnInfo(name = "notes")
    val notes: String?
)
